### ISSUE TITLE
Terrain Level does not start to generate

### ISSUE THREAD

**Issue by Juris3D** [midgen/CashDemo#4]
At first there was no character chosen for default pawn in game mode (was a spectator). With 3rd pers character chosen, Islands map generates okay, but Terrain map does not start generation.
P.S.: how shore filters can be used? Thank You for work on this. A big one.

**Comment by midgen** [comment]
SHA-1: 8b34e417e0b2542d087d51553def6da4e20b8827

* Fixed gamemodes and level settings for cashgen samples
