### ISSUE TITLE
Can't run project in 4.24.3 version of unreal engine.

### ISSUE THREAD

**Issue by aleksandrasjudelis** [midgen/CashDemo#6]
Project was git cloned with all submodules.
When trying to run the project by double clinking CashDemo.uproject

![Capture](https://user-images.githubusercontent.com/17637472/80312184-7a2ca800-87ec-11ea-9a6f-a3432fa353f1.PNG)

Clicked yes, then I get this error.

![Capturse](https://user-images.githubusercontent.com/17637472/80312185-7ac53e80-87ec-11ea-9cdd-27d61628f3cf.PNG)

When trying to run the project from Visual Studio 2019

![Captusssre](https://user-images.githubusercontent.com/17637472/80312186-7b5dd500-87ec-11ea-95ee-838a9e49cdd4.PNG)

I don't know what I am doing wrong here.

**Comment by midgen** [comment]
Hrm, I might have accidentally submitted a broken version, I'm in the middle of a refactor. I've just submitted an updated version. 

390626f18773f786645fff61f4a7262dc9dfd860

**Comment by aleksandrasjudelis** [comment]
Hm, strange I cloned the project again with submodules but still getting same errors

**Comment by midgen** [comment]
I've fixed up a bunch of things today, and updated most plugins. I'm done a clean build on 4.24.3 and it's working fine for me.

**Comment by midgen** [comment]
Closing as no response. Feel free to reopen!
