### ISSUE TITLE
It would be great if adding some explanation for the demo

### ISSUE THREAD

**Issue by JetBelson** [midgen/CashDemo#7]
I cloned the demo project as well as all plugins.

Then went to the _Demos_ directory, went to the _UESVON_ directory, loaded the UESVON_Demo level, and clicked the play button. (Nothing Happened) 

Clicked the stop button, the following message log came out:

Blueprint Runtime Error: "Accessed None trying to read property K2Node_DynamicCast_AsActor". Blueprint:  BTDecorator_TargetGreaterThan Function:  Perform Condition Check Graph:  PerformConditionCheck Node:  Return Node

UE 4.25 + VS2019

I also checked the UESVON plugin repo, but still cannot work it out.
Many thanks for your help.

![image](https://user-images.githubusercontent.com/43242747/82139385-f9e0ec00-9859-11ea-85ad-11bc2e2af25d.png)
![image](https://user-images.githubusercontent.com/43242747/82139392-01a09080-985a-11ea-82d9-478749d29e80.png)

**Comment by midgen** [comment]
I've updated a couple of assets that weren't configured right that were causing the error spam. It should have worked fine still.

There's just a simple AI agent that follows the player around using the 3d navigation system.
